export type CategoryPreset = {
  key: string;
  name: string;
  nameAr: string;
};

export type BusinessCategoryPreset = {
  label: string;
  labelAr: string;
  categories: CategoryPreset[];
};

const category = (key: string, name: string, nameAr: string): CategoryPreset => ({
  key,
  name,
  nameAr,
});

const groceryCategories: CategoryPreset[] = [
  category("fresh-produce", "Fresh Produce", "خضار وفواكه"),
  category("dairy-eggs", "Dairy & Eggs", "ألبان وبيض"),
  category("meat-poultry", "Meat & Poultry", "لحوم ودواجن"),
  category("bakery", "Bakery", "مخبوزات"),
  category("frozen-foods", "Frozen Foods", "أطعمة مجمدة"),
  category("pantry", "Pantry", "مواد تموينية"),
  category("snacks-sweets", "Snacks & Sweets", "تسالي وحلويات"),
  category("beverages", "Beverages", "مشروبات"),
  category("water", "Water", "مياه"),
  category("cleaning-supplies", "Cleaning Supplies", "مواد تنظيف"),
  category("personal-care", "Personal Care", "عناية شخصية"),
  category("baby-products", "Baby Products", "مستلزمات أطفال"),
  category("household", "Household", "مستلزمات منزلية"),
  category("pet-supplies", "Pet Supplies", "مستلزمات حيوانات أليفة"),
];

export const BUSINESS_CATEGORY_PRESETS: Record<string, BusinessCategoryPreset> = {
  supermarket: {
    label: "Supermarket / Hypermarket",
    labelAr: "سوبرماركت / هايبرماركت",
    categories: groceryCategories,
  },
  grocery: {
    label: "Grocery store",
    labelAr: "بقالة",
    categories: groceryCategories,
  },
  mini_market: {
    label: "Mini-market / Convenience store",
    labelAr: "ميني ماركت / تموينات",
    categories: groceryCategories,
  },
  restaurant: {
    label: "Restaurant",
    labelAr: "مطعم",
    categories: [
      category("appetizers", "Appetizers", "مقبلات"),
      category("main-courses", "Main Courses", "أطباق رئيسية"),
      category("grills", "Grills", "مشاوي"),
      category("sandwiches", "Sandwiches", "سندويشات"),
      category("salads", "Salads", "سلطات"),
      category("sides", "Side Dishes", "أطباق جانبية"),
      category("soups", "Soups", "شوربات"),
      category("desserts", "Desserts", "حلويات"),
      category("drinks", "Drinks", "مشروبات"),
      category("family-meals", "Family Meals", "وجبات عائلية"),
    ],
  },
  fast_food: {
    label: "Fast food",
    labelAr: "وجبات سريعة",
    categories: [
      category("meals", "Meals", "وجبات"),
      category("burgers", "Burgers", "برغر"),
      category("fried-chicken", "Fried Chicken", "دجاج مقلي"),
      category("pizza", "Pizza", "بيتزا"),
      category("sandwiches", "Sandwiches", "سندويشات"),
      category("sides", "Sides", "أطباق جانبية"),
      category("kids-meals", "Kids Meals", "وجبات أطفال"),
      category("desserts", "Desserts", "حلويات"),
      category("drinks", "Drinks", "مشروبات"),
    ],
  },
  bakery: {
    label: "Bakery / Sweets",
    labelAr: "مخبز / حلويات",
    categories: [
      category("bread", "Bread", "خبز"),
      category("pastries", "Pastries", "معجنات"),
      category("cakes", "Cakes", "كيك"),
      category("arabic-sweets", "Arabic Sweets", "حلويات عربية"),
      category("western-desserts", "Western Desserts", "حلويات غربية"),
      category("cookies", "Cookies & Biscuits", "كوكيز وبسكويت"),
      category("party-trays", "Party Trays", "صواني مناسبات"),
      category("drinks", "Drinks", "مشروبات"),
    ],
  },
  cafe: {
    label: "Café",
    labelAr: "مقهى / كوفي شوب",
    categories: [
      category("hot-coffee", "Hot Coffee", "قهوة ساخنة"),
      category("cold-coffee", "Cold Coffee", "قهوة باردة"),
      category("tea", "Tea", "شاي"),
      category("cold-drinks", "Cold Drinks", "مشروبات باردة"),
      category("smoothies", "Smoothies", "سموذي"),
      category("breakfast", "Breakfast", "فطور"),
      category("sandwiches", "Sandwiches", "سندويشات"),
      category("desserts", "Desserts", "حلويات"),
    ],
  },
  butcher: {
    label: "Butcher",
    labelAr: "ملحمة",
    categories: [
      category("beef", "Beef", "لحوم بقر"),
      category("lamb", "Lamb", "لحوم خروف"),
      category("chicken", "Chicken", "دجاج"),
      category("minced-meat", "Minced Meat", "لحمة مفرومة"),
      category("fresh-cuts", "Fresh Cuts", "قطع طازجة"),
      category("marinated-meat", "Marinated Meat", "لحوم متبلة"),
      category("frozen-meat", "Frozen Meat", "لحوم مجمدة"),
      category("bbq-packs", "BBQ Packs", "تجهيزات مشاوي"),
    ],
  },
  produce: {
    label: "Fruit and vegetable store",
    labelAr: "خضار وفواكه",
    categories: [
      category("vegetables", "Vegetables", "خضار"),
      category("fruits", "Fruits", "فواكه"),
      category("herbs", "Fresh Herbs", "أعشاب طازجة"),
      category("dates", "Dates", "تمور"),
      category("nuts", "Nuts", "مكسرات"),
      category("organic", "Organic", "منتجات عضوية"),
      category("ready-boxes", "Ready Boxes", "صناديق جاهزة"),
    ],
  },
  frozen_food: {
    label: "Frozen food store",
    labelAr: "مواد غذائية مجمدة",
    categories: [
      category("frozen-meat", "Frozen Meat", "لحوم مجمدة"),
      category("frozen-poultry", "Frozen Poultry", "دواجن مجمدة"),
      category("frozen-seafood", "Frozen Seafood", "مأكولات بحرية مجمدة"),
      category("frozen-vegetables", "Frozen Vegetables", "خضار مجمدة"),
      category("frozen-pastries", "Frozen Pastries", "معجنات مجمدة"),
      category("ready-meals", "Ready Meals", "وجبات جاهزة"),
      category("ice-cream", "Ice Cream", "بوظة وآيس كريم"),
    ],
  },
  clothing: {
    label: "Clothing",
    labelAr: "ملابس",
    categories: [
      category("men", "Men", "رجالي"),
      category("women", "Women", "نسائي"),
      category("kids", "Kids", "أطفال"),
      category("babies", "Babies", "مواليد"),
      category("sportswear", "Sportswear", "ملابس رياضية"),
      category("underwear", "Underwear", "ملابس داخلية"),
      category("accessories", "Accessories", "إكسسوارات"),
      category("seasonal", "Seasonal", "موسمي"),
    ],
  },
  shoes: {
    label: "Shoes",
    labelAr: "أحذية",
    categories: [
      category("men-shoes", "Men's Shoes", "أحذية رجالية"),
      category("women-shoes", "Women's Shoes", "أحذية نسائية"),
      category("kids-shoes", "Kids' Shoes", "أحذية أطفال"),
      category("sports-shoes", "Sports Shoes", "أحذية رياضية"),
      category("formal-shoes", "Formal Shoes", "أحذية رسمية"),
      category("sandals", "Sandals", "صنادل"),
      category("slippers", "Slippers", "شباشب"),
      category("shoe-care", "Shoe Care", "عناية بالأحذية"),
    ],
  },
  jewelry: {
    label: "Jewelry",
    labelAr: "مجوهرات",
    categories: [
      category("rings", "Rings", "خواتم"),
      category("necklaces", "Necklaces", "قلائد"),
      category("bracelets", "Bracelets", "أساور"),
      category("earrings", "Earrings", "أقراط"),
      category("watches", "Watches", "ساعات"),
      category("sets", "Jewelry Sets", "أطقم مجوهرات"),
      category("silver", "Silver", "فضة"),
      category("gold", "Gold", "ذهب"),
    ],
  },
  cosmetics: {
    label: "Cosmetics / Beauty",
    labelAr: "مستحضرات تجميل / عناية",
    categories: [
      category("makeup", "Makeup", "مكياج"),
      category("skin-care", "Skin Care", "عناية بالبشرة"),
      category("hair-care", "Hair Care", "عناية بالشعر"),
      category("body-care", "Body Care", "عناية بالجسم"),
      category("nails", "Nails", "أظافر"),
      category("beauty-tools", "Beauty Tools", "أدوات تجميل"),
      category("mens-grooming", "Men's Grooming", "عناية رجالية"),
    ],
  },
  perfume: {
    label: "Perfume",
    labelAr: "عطور",
    categories: [
      category("women-perfume", "Women's Perfume", "عطور نسائية"),
      category("men-perfume", "Men's Perfume", "عطور رجالية"),
      category("unisex", "Unisex", "عطور مشتركة"),
      category("arabic-perfume", "Arabic Perfume", "عطور عربية"),
      category("oud", "Oud", "عود"),
      category("incense", "Incense", "بخور"),
      category("gift-sets", "Gift Sets", "أطقم هدايا"),
    ],
  },
  electronics: {
    label: "Electronics",
    labelAr: "إلكترونيات",
    categories: [
      category("televisions", "Televisions", "شاشات وتلفزيونات"),
      category("audio", "Audio", "صوتيات"),
      category("cameras", "Cameras", "كاميرات"),
      category("gaming", "Gaming", "ألعاب إلكترونية"),
      category("smart-home", "Smart Home", "منزل ذكي"),
      category("wearables", "Wearables", "أجهزة قابلة للارتداء"),
      category("accessories", "Accessories", "إكسسوارات"),
      category("cables-adapters", "Cables & Adapters", "كوابل ومحولات"),
    ],
  },
  computers: {
    label: "Computers",
    labelAr: "كمبيوتر",
    categories: [
      category("laptops", "Laptops", "لابتوبات"),
      category("desktops", "Desktop Computers", "أجهزة مكتبية"),
      category("monitors", "Monitors", "شاشات كمبيوتر"),
      category("components", "Computer Components", "قطع كمبيوتر"),
      category("storage", "Storage", "وحدات تخزين"),
      category("networking", "Networking", "شبكات"),
      category("printers", "Printers", "طابعات"),
      category("accessories", "Accessories", "إكسسوارات"),
    ],
  },
  mobile_phones: {
    label: "Mobile phones and accessories",
    labelAr: "هواتف وإكسسوارات",
    categories: [
      category("mobile-phones", "Mobile Phones", "هواتف محمولة"),
      category("phone-cases", "Phone Cases", "كفرات هواتف"),
      category("chargers", "Chargers", "شواحن"),
      category("cables", "Cables", "كوابل"),
      category("screen-protectors", "Screen Protectors", "حماية شاشات"),
      category("earbuds-headphones", "Earbuds & Headphones", "سماعات"),
      category("power-banks", "Power Banks", "بطاريات متنقلة"),
      category("smart-watches", "Smart Watches", "ساعات ذكية"),
      category("repair-parts", "Repair Parts", "قطع صيانة"),
    ],
  },
  furniture: {
    label: "Furniture",
    labelAr: "أثاث",
    categories: [
      category("living-room", "Living Room", "غرف معيشة"),
      category("bedroom", "Bedroom", "غرف نوم"),
      category("dining-room", "Dining Room", "غرف سفرة"),
      category("office", "Office Furniture", "أثاث مكتبي"),
      category("outdoor", "Outdoor Furniture", "أثاث خارجي"),
      category("mattresses", "Mattresses", "فرشات"),
      category("storage", "Storage", "خزائن وتخزين"),
      category("kids-furniture", "Kids Furniture", "أثاث أطفال"),
    ],
  },
  home_appliances: {
    label: "Home appliances",
    labelAr: "أجهزة منزلية",
    categories: [
      category("refrigerators", "Refrigerators", "ثلاجات"),
      category("washing-machines", "Washing Machines", "غسالات"),
      category("ovens-cookers", "Ovens & Cookers", "أفران وطباخات"),
      category("air-conditioning", "Air Conditioning", "مكيفات"),
      category("small-appliances", "Small Appliances", "أجهزة منزلية صغيرة"),
      category("vacuum-cleaners", "Vacuum Cleaners", "مكانس كهربائية"),
      category("water-dispensers", "Water Dispensers", "برادات مياه"),
      category("spare-parts", "Spare Parts", "قطع غيار"),
    ],
  },
  home_decor: {
    label: "Home décor",
    labelAr: "ديكور منزلي",
    categories: [
      category("lighting", "Lighting", "إنارة"),
      category("rugs", "Rugs", "سجاد"),
      category("curtains", "Curtains", "ستائر"),
      category("wall-decor", "Wall Décor", "ديكور حائط"),
      category("mirrors", "Mirrors", "مرايا"),
      category("kitchen-decor", "Kitchen Décor", "ديكور مطبخ"),
      category("bathroom-decor", "Bathroom Décor", "ديكور حمام"),
      category("candles-scents", "Candles & Home Scents", "شموع ومعطرات منزل"),
    ],
  },
  auto_parts: {
    label: "Auto parts",
    labelAr: "قطع سيارات",
    categories: [
      category("body-parts", "Body Parts", "قطع بودي"),
      category("lighting", "Lighting", "إضاءة"),
      category("suspension", "Suspension", "تعليق"),
      category("steering", "Steering", "توجيه"),
      category("brakes", "Brakes", "فرامل"),
      category("engine-parts", "Engine Parts", "قطع محرك"),
      category("cooling-system", "Cooling System", "نظام تبريد"),
      category("air-conditioning", "Air Conditioning", "تكييف"),
      category("electrical-parts", "Electrical Parts", "قطع كهرباء"),
      category("filters-maintenance", "Filters & Maintenance", "فلاتر وصيانة"),
      category("interior-exterior", "Interior & Exterior", "داخلي وخارجي"),
      category("used-parts", "Used Parts", "قطع مستعملة"),
    ],
  },
  tires: {
    label: "Tires and car accessories",
    labelAr: "إطارات وإكسسوارات سيارات",
    categories: [
      category("tires", "Tires", "إطارات"),
      category("wheels", "Wheels", "جنوط"),
      category("wheel-parts", "Wheel Parts", "قطع عجلات"),
      category("car-accessories", "Car Accessories", "إكسسوارات سيارات"),
      category("oils-fluids", "Oils & Fluids", "زيوت وسوائل"),
      category("wipers", "Wipers", "مساحات"),
      category("car-care", "Car Care", "عناية بالسيارة"),
      category("tools", "Tools", "أدوات"),
    ],
  },
  hardware: {
    label: "Hardware store",
    labelAr: "عدد وأدوات",
    categories: [
      category("hand-tools", "Hand Tools", "عدد يدوية"),
      category("power-tools", "Power Tools", "عدد كهربائية"),
      category("fasteners", "Fasteners", "براغي ومثبتات"),
      category("paint", "Paint", "دهانات"),
      category("safety", "Safety Equipment", "معدات سلامة"),
      category("locks", "Locks", "أقفال"),
      category("adhesives", "Adhesives", "مواد لاصقة"),
      category("garden", "Garden Tools", "أدوات حدائق"),
    ],
  },
  building_materials: {
    label: "Building materials",
    labelAr: "مواد بناء",
    categories: [
      category("cement", "Cement", "إسمنت"),
      category("steel", "Steel", "حديد"),
      category("blocks", "Blocks", "طوب وبلوك"),
      category("insulation", "Insulation", "عزل"),
      category("roofing", "Roofing", "مواد أسقف"),
      category("tiles", "Tiles", "بلاط"),
      category("wood", "Wood", "خشب"),
      category("sand-aggregate", "Sand & Aggregate", "رمل وحصمة"),
    ],
  },
  electrical_supplies: {
    label: "Electrical supplies",
    labelAr: "مواد كهربائية",
    categories: [
      category("cables-wires", "Cables & Wires", "كوابل وأسلاك"),
      category("switches-sockets", "Switches & Sockets", "مفاتيح وأباريز"),
      category("breakers", "Breakers", "قواطع كهربائية"),
      category("lighting", "Lighting", "إنارة"),
      category("panels", "Electrical Panels", "لوحات كهربائية"),
      category("conduits", "Conduits", "مواسير كهرباء"),
      category("industrial", "Industrial Electrical", "كهرباء صناعية"),
      category("electrical-tools", "Electrical Tools", "أدوات كهربائية"),
    ],
  },
  plumbing: {
    label: "Plumbing supplies",
    labelAr: "مواد صحية وسباكة",
    categories: [
      category("pipes", "Pipes", "مواسير"),
      category("fittings", "Fittings", "وصلات"),
      category("faucets", "Faucets", "خلاطات وحنفيات"),
      category("sanitaryware", "Sanitaryware", "أدوات صحية"),
      category("valves", "Valves", "محابس"),
      category("pumps", "Pumps", "مضخات"),
      category("water-heaters", "Water Heaters", "سخانات مياه"),
      category("drainage", "Drainage", "تصريف"),
    ],
  },
  tools: {
    label: "Tools and equipment",
    labelAr: "أدوات ومعدات",
    categories: [
      category("hand-tools", "Hand Tools", "أدوات يدوية"),
      category("power-tools", "Power Tools", "أدوات كهربائية"),
      category("measuring-tools", "Measuring Tools", "أدوات قياس"),
      category("welding", "Welding", "لحام"),
      category("air-tools", "Air Tools", "أدوات هوائية"),
      category("safety", "Safety Equipment", "معدات سلامة"),
      category("tool-storage", "Tool Storage", "تخزين أدوات"),
      category("accessories", "Accessories", "ملحقات"),
    ],
  },
  pharmacy: {
    label: "Pharmacy",
    labelAr: "صيدلية",
    categories: [
      category("otc-medicines", "OTC Medicines", "أدوية بدون وصفة"),
      category("vitamins", "Vitamins", "فيتامينات"),
      category("personal-care", "Personal Care", "عناية شخصية"),
      category("baby-care", "Baby Care", "عناية بالأطفال"),
      category("first-aid", "First Aid", "إسعافات أولية"),
      category("medical-devices", "Medical Devices", "أجهزة طبية"),
      category("skin-care", "Skin Care", "عناية بالبشرة"),
      category("hair-care", "Hair Care", "عناية بالشعر"),
      category("oral-care", "Oral Care", "عناية بالفم والأسنان"),
    ],
  },
  pet_supplies: {
    label: "Pet supplies",
    labelAr: "مستلزمات حيوانات أليفة",
    categories: [
      category("dogs", "Dogs", "كلاب"),
      category("cats", "Cats", "قطط"),
      category("birds", "Birds", "طيور"),
      category("fish", "Fish", "أسماك"),
      category("small-pets", "Small Pets", "حيوانات صغيرة"),
      category("pet-food", "Pet Food", "طعام حيوانات"),
      category("treats", "Treats", "مكافآت"),
      category("grooming", "Grooming", "عناية ونظافة"),
      category("accessories", "Accessories", "إكسسوارات"),
    ],
  },
  flowers: {
    label: "Flowers",
    labelAr: "زهور",
    categories: [
      category("bouquets", "Bouquets", "باقات"),
      category("roses", "Roses", "ورود"),
      category("plants", "Plants", "نباتات"),
      category("weddings", "Weddings", "أعراس"),
      category("events", "Events", "مناسبات"),
      category("flower-gifts", "Flower Gifts", "هدايا مع ورد"),
      category("vases", "Vases", "مزهريات"),
    ],
  },
  gifts: {
    label: "Gifts",
    labelAr: "هدايا",
    categories: [
      category("gifts-for-him", "Gifts for Him", "هدايا له"),
      category("gifts-for-her", "Gifts for Her", "هدايا لها"),
      category("kids-gifts", "Kids Gifts", "هدايا أطفال"),
      category("occasions", "Occasions", "مناسبات"),
      category("personalized", "Personalized Gifts", "هدايا مخصصة"),
      category("gift-wrapping", "Gift Wrapping", "تغليف هدايا"),
      category("cards", "Cards", "بطاقات"),
    ],
  },
  toys: {
    label: "Toys",
    labelAr: "ألعاب",
    categories: [
      category("baby-toys", "Baby Toys", "ألعاب رضع"),
      category("preschool", "Preschool", "ما قبل المدرسة"),
      category("boys", "Boys", "أولاد"),
      category("girls", "Girls", "بنات"),
      category("educational", "Educational Toys", "ألعاب تعليمية"),
      category("outdoor", "Outdoor Toys", "ألعاب خارجية"),
      category("games-puzzles", "Games & Puzzles", "ألعاب وألغاز"),
      category("vehicles", "Toy Vehicles", "سيارات ألعاب"),
      category("dolls", "Dolls", "دمى"),
    ],
  },
  books_stationery: {
    label: "Books and stationery",
    labelAr: "كتب وقرطاسية",
    categories: [
      category("arabic-books", "Arabic Books", "كتب عربية"),
      category("english-books", "English Books", "كتب إنجليزية"),
      category("school-supplies", "School Supplies", "لوازم مدرسية"),
      category("office-supplies", "Office Supplies", "لوازم مكتبية"),
      category("art-supplies", "Art Supplies", "لوازم فنية"),
      category("notebooks", "Notebooks", "دفاتر"),
      category("pens", "Pens & Writing", "أقلام وكتابة"),
      category("printing", "Printing Supplies", "مستلزمات طباعة"),
    ],
  },
  sports: {
    label: "Sports equipment",
    labelAr: "معدات رياضية",
    categories: [
      category("fitness", "Fitness", "لياقة بدنية"),
      category("football", "Football", "كرة قدم"),
      category("basketball", "Basketball", "كرة سلة"),
      category("racket-sports", "Racket Sports", "رياضات المضرب"),
      category("swimming", "Swimming", "سباحة"),
      category("outdoor-sports", "Outdoor Sports", "رياضات خارجية"),
      category("sports-clothing", "Sports Clothing", "ملابس رياضية"),
      category("sports-shoes", "Sports Shoes", "أحذية رياضية"),
      category("accessories", "Accessories", "إكسسوارات"),
    ],
  },
  other: {
    label: "Other business",
    labelAr: "نشاط آخر",
    categories: [
      category("new-arrivals", "New Arrivals", "وصل حديثاً"),
      category("best-sellers", "Best Sellers", "الأكثر مبيعاً"),
      category("offers", "Offers", "عروض"),
      category("featured", "Featured", "مميز"),
      category("general", "General", "عام"),
    ],
  },
};

export function getBusinessCategoryPreset(
  businessType: string | null | undefined,
  businessTypeOther?: string | null
): BusinessCategoryPreset {
  const preset = BUSINESS_CATEGORY_PRESETS[businessType || "other"];

  if (preset) return preset;

  return {
    ...BUSINESS_CATEGORY_PRESETS.other,
    label: businessTypeOther?.trim() || "Other business",
    labelAr: "نشاط آخر",
  };
}
